# generate-secrets-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: generate-secrets
  namespace: mastodon
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: generate-secrets
        image: ghcr.io/mastodon/mastodon:v4.3.1
        command: 
        - /bin/bash
        - -c
        - |
          echo "=== Generating encryption keys ==="
          bundle exec rails db:encryption:init
          echo ""
          echo "=== Generating VAPID keys ==="
          bundle exec rails mastodon:webpush:generate_vapid_key
          echo ""
          echo "=== Generating SECRET_KEY_BASE ==="
          echo "SECRET_KEY_BASE=$(bundle exec rails secret)"
          echo ""
          echo "=== Generating OTP_SECRET ==="
          echo "OTP_SECRET=$(bundle exec rails secret)"

        