apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mastodon-media
  namespace: mastodon
spec:
  storageClassName: shared-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi