apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: mastodon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine
        env:
        - name: POSTGRES_USER
          value: mastodon
        - name: POSTGRES_PASSWORD
          value: mastodon_db_password  # Change this!
        - name: POSTGRES_DB
          value: mastodon_production
        - name: POSTGRES_HOST_AUTH_METHOD
          value: md5
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres  # Important for PostgreSQL
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
